# Generated by Django 4.2.3 on 2023-09-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=59)),
                ('email', models.EmailField(max_length=111)),
                ('password', models.CharField(max_length=44)),
            ],
        ),
    ]
